Tuotteiden poistaminen 100
ohtuprojekti-Kierratysavustin/Kierratysavustin pull request #110
Opened 2021-09-24 09:10 UTC by juhakaup

# Tuotteen poistaminen #100 

Frontend muutokset
- Poista tuote -nappi omana komponenttinaan.
- Nappi näkymään tuotteen lisänneelle käyttäjälle tuotelistassa ja tuotesivulla
- Product serviceen remove -funktio
- Productin tyypitykseen lisätty user-kenttä

Backendin muutokset
- Tuotteen tietoihin lisätään käyttäjän id, muutokset skemaan ja routeriin
- Routeriin poiston toiminnallisuus
- Yksikkötestit tarkastavat tietokantamallin tuotteen osalta, tuotteen poiston onnistumisen validin käyttäjän toimesta ja epäonnistumisen epävalidin käyttäjän kohdalla.

e2e testit tarkastavat että nappi poistaa tuotteen

2021-09-25 09:10 UTC, hackinen approved these changes
Hyvältä näyttää!

2021-09-27 08:57 UTC, LauriTahvanainen commented on server/tests/kierratysavustin_api.test.js
> +})
Ei ole apitesti, mutta sanoitkin jo aiemmin, että pitäisi pilkkoa tätä tiedostoa?

2021-09-27 08:58 UTC, LauriTahvanainen requested changes
Kysymys

2021-09-27 09:13 UTC, juhakaup commented on server/tests/kierratysavustin_api.test.js
> +})
Joo, tää voisi olla omassa tiedostossaan. Testejä vois tarkistella jossain vaiheessa enemmän.

2021-09-27 09:16 UTC, LauriTahvanainen approved these changes

2021-09-27 09:18 UTC, merged