[WIP] Instruction vote form refactor
ohtuprojekti-Kierratysavustin/Kierratysavustin pull request #152
Opened 2021-11-18 10:38 UTC by lacolegiala

# Instruction vote form refactor

- Instruction voting has been refactor to just use two endpoints, 'instructions/like' and 'instructions/dislike'. There is still one issue with the client code (when pressing either one of the buttons twice, the number 0 won't show up without refresh), hence WIP.

- Linkkaa issue (Monta linkkausta eroteltuna pilkulla)

closes #136, resolves #136, fixes #136

2021-11-19 13:00 UTC, LauriTahvanainen requested changes
Kun tein tuon backendin toimimaan kahdella resurssilla, oli mielessä jotakin tämmöistä frontille. Iffittelyt saa siis pois, sillä backend hoitaa sen. Tässä hajoaa vaan komponenttitesti, koska tuo järjestäminen tapahtuu oikeasti ProductView:ssä. 
Toinen kysymysmerkki on tuo, että muutetaan äänimäärä kun saadaan vastaus. Käyttäjä ei saa yhteytensä nopeudesta riippuen heti palautetta liken tai disliken painamisesta, mutta toisaalta vastaukseen reagointi voi kertoa käyttäjälle, että nyt se vasta reisteröitiin oikeasti.
En ole varma miten tämä suhtautuu noiden nappien spammimiseen, ja jos vaikka vastaukset tulevat eri järjestyksessä. 

Tuossa myös muuten tuohon tuotteen päivittämiseen, voi päivittää storesta yhden tuotteen updateProduct avulla

Jokatapauksessa voi käyttää, tai olla käyttämättä. Tämähän on nyt varsin toimiva ja ei kaikkea iffittelyä pidä saada revittyä pois repimisen ilosta.

https://gist.github.com/LauriTahvanainen/d5b16b88d63a3422cb30897bdc7d0aae

2021-11-19 13:00 UTC, LauriTahvanainen commented on client/src/components/forms/VoteForm.tsx
> +      .then(() => productService.getAll().then(p => setProducts(p)))
Pidemmän päälle kaikkien tuotteiden hakeminen yhden tuotteen ohjeiden päivittämistä varten ei ole tehokas ratkaisu.

2021-11-21 18:49 UTC, lacolegiala commented on client/src/components/forms/VoteForm.tsx
> +      .then(() => productService.getAll().then(p => setProducts(p)))
Tarkastelin molempia ratkaisuja ja mielestäni tämä https://gist.github.com/LauriTahvanainen/d5b16b88d63a3422cb30897bdc7d0aae on tosiaan selkeämpi ratkaisu, joten päätin käyttää sitä. Pitää vaan vielä päivittää testit sitä varten.

2021-11-29 11:52 UTC, hackinen approved these changes
Hyvältä näyttää, selkeyttää koodia kyllä huomattavasti

2021-11-30 07:27 UTC, juhakaup approved these changes
Hyvältä näyttää, huomattavasti selkeämpi toteutus.

2021-11-30 07:28 UTC, merged