Kaytto oikeus roolit 141
ohtuprojekti-Kierratysavustin/Kierratysavustin pull request #153
Opened 2021-11-19 09:34 UTC by LauriTahvanainen

Roolipohjainen käyttöoikeusjärjestelmä. Nyt kolme roolia User, Moderator, Admin. Rooli voi periä alempana hierarkiassa olevien roolit. Esim Admin on kaikki oikeudet mitkä Moderatorilla ja Userilla. 
Yksi admin resurssi ja yksi moderator resurssi. 
API testit autentikoinnista käyttäen satunnaisia resursseja. 
Pitäisikö tehdä testi suoraan tuolle autentikointifunktiolle?

Toinen asia mitä voi miettiä, on miten toteuttaa moderaattorin resurssit. Tein nyt oman, mutta ihan hyvin jo olemassaolevaan poistamisresurssiin voi lisätä tarkastuksen moderaattoriroolille.
 
resolves #141, closes #141

2021-11-24 18:22 UTC, juhakaup requested changes
Omat routet korkeammille käyttäjätasoille tuntuu ehkä hieman hankalalta, toki moderointiin liittyvät asiat voi laittaa erikseen.

Olisikohan järkevää tehdä käyttöoikeuden todentaminen keskitetysti tuolla auth.js:ssä esim. funktio(i)lla joka saa käyttäjän, toimintoon liittyvän objektin ja vaadittavan käyttäjätason. Tällöin voitaisiin katsoa onko käyttäjä objektin luoja, tai onko käyttäjällä tarvittavat oikeudet muokata muiden luomaa materiaalia. Tällä saisi myös noita routereita hieman siistimmiksi.

Toki herää kysymys, onko käyttäjällä oikeus tehdä kaikkea mahdollista omalle sisällölleen, vai pitäisikö esim tuotteen poistamista rajoittaa ja miten se sitten toteutettaisiin.

2021-11-26 14:19 UTC, LauriTahvanainen commented
> Omat routet korkeammille käyttäjätasoille tuntuu ehkä hieman hankalalta, toki moderointiin liittyvät asiat voi laittaa erikseen.
> 
> Olisikohan järkevää tehdä käyttöoikeuden todentaminen keskitetysti tuolla auth.js:ssä esim. funktio(i)lla joka saa käyttäjän, toimintoon liittyvän objektin ja vaadittavan käyttäjätason. Tällöin voitaisiin katsoa onko käyttäjä objektin luoja, tai onko käyttäjällä tarvittavat oikeudet muokata muiden luomaa materiaalia. Tällä saisi myös noita routereita hieman siistimmiksi.
> 
> Toki herää kysymys, onko käyttäjällä oikeus tehdä kaikkea mahdollista omalle sisällölleen, vai pitäisikö esim tuotteen poistamista rajoittaa ja miten se sitten toteutettaisiin.

Niin, rajoituksena voi tulla esimerkiksi sellainen, että tuotteita joilla on jo ohjeita ei voi poistaa. Tuohan olisi kuitenkin hyvinkin resurssikohtainen tarkastus.

2021-11-26 15:01 UTC, LauriTahvanainen commented
Mitenkä jos jättää tuon moderator routerin kuitenkin tuonne? Sinne voi laittaa sitten sellaista oikeasti vain moderaattoreille tehtyä.

2021-11-26 15:28 UTC, juhakaup commented
> Mitenkä jos jättää tuon moderator routerin kuitenkin tuonne? Sinne voi laittaa sitten sellaista oikeasti vain moderaattoreille tehtyä.

Se on varmaan ihan järkevää.

2021-11-27 12:56 UTC, LauriTahvanainen commented
Haitko jotakin tämmöistä?

2021-11-27 14:13 UTC, juhakaup approved these changes

2021-11-29 10:34 UTC, lacolegiala approved these changes

2021-11-29 14:38 UTC, merged